name: Packages

concurrency:
  group: packages-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock
  push:
    branches: [main]
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - snack-babel-standalone
          - snack-content
          - snack-eslint-standalone
          - snack-proxies
          - snack-require-context
          - snack-sdk
          - snack-term
        include:
          - package: snack-babel-standalone
            local-install: true
          - package: snack-eslint-standalone
            local-install: true
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: ğŸ“¦ Install monorepo dependencies
        run: yarn install --frozen-lockfile

      # When decoupled from the monorepo, make sure to install the local packages
      - name: ğŸ“¦ Install local dependencies
        if: ${{ matrix.local-install }}
        run: yarn install --frozen-lockfile
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ›  Build core packages
        run: yarn build

      - name: ğŸš¨ Lint package
        run: yarn lint --max-warnings 0
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ§ª Test package
        run: yarn test --ci --maxWorkers 1
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ›  Build package
        run: yarn build
        working-directory: packages/${{ matrix.package }}
