name: Packages

concurrency:
  group: packages-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock
  push:
    branches: [main]
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - snack-babel-standalone
          - snack-content
          - snack-eslint-standalone
          - snack-proxies
          - snack-require-context
          - snack-runtime
          - snack-sdk
          - snack-term
        include:
          - package: snack-babel-standalone
            monorepo-detached: true
          - package: snack-eslint-standalone
            monorepo-detached: true
          - package: snack-runtime
            monorepo-detached: true
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: ğŸ“¦ Install monorepo dependencies
        run: yarn install --frozen-lockfile

      # When decoupled from the monorepo, make sure to install the local packages
      - name: ğŸ“¦ Install local dependencies
        if: ${{ matrix.monorepo-detached }}
        run: yarn install --frozen-lockfile
        working-directory: packages/${{ matrix.package }}

      # When coupled within the monorepo, build the package and all its dependents
      - name: ğŸ›  Build dependent packages
        if: ${{ !matrix.monorepo-detached }}
        run: yarn turbo build --filter "{./packages/${{ matrix.package }}}..."

      - name: ğŸš¨ Lint package
        run: yarn lint --max-warnings 0
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ§ª Test package
        run: yarn test --ci --maxWorkers 1
        working-directory: packages/${{ matrix.package }}

      # When decoupled from the monorepo, make sure the package is built
      # Since there are no dependents, do this step last to fail faster
      - name: ğŸ›  Build package
        if: ${{ matrix.monorepo-detached }}
        run: yarn build
        working-directory: packages/${{ matrix.package }}
