name: Packages

concurrency:
  group: packages-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock
  push:
    branches: [main]
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - snack-babel-standalone
          - snack-content
          - snack-eslint-standalone
          - snack-proxies
          - snack-require-context
          - snack-runtime
          - snack-sdk
          - snack-term
        include:
          - package: snack-babel-standalone
            monorepo-detached: true
          - package: snack-eslint-standalone
            monorepo-detached: true
          - package: snack-runtime
            monorepo-detached: true
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      # Cache the build files when coupled within the monorepo
      - name: ğŸ— Setup caching
        uses: actions/cache@v3
        if: ${{ !matrix.monorepo-detached }}
        with:
          key: turbo-${{ matrix.package }}-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ matrix.package }}-${{ runner.os }}
            turbo-${{ matrix.package }}
          path: |
            node_modules/.cache/turbo
            packages/*/.turbo

      - name: ğŸ“¦ Install dependencies
        run: yarn install --frozen-lockfile

      - name: ğŸš¨ Lint package
        if: ${{ !matrix.monorepo-detached }}
        run: yarn turbo lint -- --filter "./packages/${{ matrix.package }}" -- --max-warnings 0

      - name: ğŸ§ª Test package
        if: ${{ !matrix.monorepo-detached }}
        run: yarn turbo test -- --filter "./packages/${{ matrix.package }}" -- --ci --maxWorkers 1

      - name: ğŸ›  Build package
        if: ${{ !matrix.monorepo-detached }}
        run: yarn turbo build -- --filter "{./packages/${{ matrix.package }}}..."

      # When decoupled from the monorepo, make sure to install the local packages
      - name: ğŸ“¦ Install detached dependencies
        if: ${{ matrix.monorepo-detached }}
        run: yarn install --frozen-lockfile
        working-directory: packages/${{ matrix.package }}

      - name: ğŸš¨ Lint detached package
        if: ${{ matrix.monorepo-detached }}
        run: yarn lint --max-warnings 0
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ§ª Test detached package
        if: ${{ matrix.monorepo-detached }}
        run: yarn test --ci --maxWorkers 1
        working-directory: packages/${{ matrix.package }}

      # When decoupled from the monorepo, make sure the package is built
      # Since there are no dependents, do this step last to fail faster
      - name: ğŸ›  Build detached package
        if: ${{ matrix.monorepo-detached }}
        run: yarn build
        working-directory: packages/${{ matrix.package }}
