name: Packages

concurrency:
  group: packages-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - pnpm-lock.yaml
      - pnpm-workspace.yaml

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - snack-babel-standalone
          - snack-content
          - snack-eslint-standalone
          - snack-proxies
          - snack-sdk
          - snack-term
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸš¨ Lint package
        run: pnpm run lint --max-warnings 0
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ§ª Test package
        run: pnpm run test --ci --maxWorkers 1
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ›  Build package
        run: pnpm run build
        working-directory: packages/${{ matrix.package }}
