name: Packages

concurrency:
  group: packages-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock
  push:
    branches: [main]
    paths:
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - snack-content
          - snack-proxies
          - snack-sdk
          - snack-term
        include:
          - package: snack-sdk
            validate-docs: true
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      
      - name: ğŸ“¦ Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      
      - name: ğŸ›  Build core packages
        run: yarn build

      - name: ğŸš¨ Lint package
        run: yarn lint --max-warnings 0
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ§ª Test package
        run: yarn test --ci --maxWorkers 1
        working-directory: packages/${{ matrix.package }}
      
      - name: ğŸ›  Build package
        run: yarn build
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ“‹ Validate docs
        if: ${{ matrix.validate-docs }}
        run: yarn doc:ci
        working-directory: packages/${{ matrix.package }}
