name: Packages

concurrency:
  group: packages-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/actions/setup-cache/**
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock
      - turbo.json
  push:
    branches: [main]
    paths:
      - .github/actions/setup-cache/**
      - .github/workflows/packages.yml
      - packages/**
      - .eslint*
      - .prettier*
      - yarn.lock
      - turbo.json

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - snack-babel-standalone
          - snack-content
          - snack-eslint-standalone
          - snack-proxies
          - snack-require-context
          - snack-runtime
          - snack-sdk
          - snack-term
        include:
          - package: snack-babel-standalone
            monorepo-detached: true
          - package: snack-eslint-standalone
            monorepo-detached: true
          - package: snack-runtime
            monorepo-detached: true
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: ğŸ— Setup cache
        uses: ./.github/actions/setup-cache

      # When coupled within the monorepo, make sure to build all packages related to the tested one
      - name: ğŸ›  Build dependencies
        if: ${{ !matrix.monorepo-detached }}
        run: yarn turbo build --filter "{./packages/${{ matrix.package }}}^..."

      # When decoupled from the monorepo, make sure to install the local packages
      - name: ğŸ“¦ Install local dependencies
        if: ${{ matrix.monorepo-detached }}
        run: yarn install --frozen-lockfile
        working-directory: packages/${{ matrix.package }}

      - name: ğŸš¨ Lint package
        run: yarn lint --max-warnings 0
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ§ª Test package
        run: yarn test --ci --maxWorkers 1
        working-directory: packages/${{ matrix.package }}

      - name: ğŸ›  Build package
        run: yarn build
        working-directory: packages/${{ matrix.package }}
