name: SnackagerProduction

defaults:
  run:
    working-directory: snackager

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'type "deploy" to confirm deploy to production (main branch only)'
        required: false
  push:
    branches: [main]
    paths:
      - .github/workflows/snackager-production.yml
      - snackager/**
      - packages/snack-sdk/**
      - .eslint*
      - .prettier*
      - yarn.lock

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup secrets
        uses: sliteteam/github-action-git-crypt-unlock@a09ea5079c1b0e1887d4c8d7a4b20f00b5c2d06b
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: ğŸ— Setup snackager
        uses: ./.github/actions/setup-snackager

      - name: ğŸš¨ Lint snackager
        run: yarn lint --max-warnings 0

      - name: ğŸ§ª Unit test snackager
        run: yarn test --ci --testPathIgnorePatterns=__integration-tests__

      # Takes a long time, best not to run this before deployment
      # - name: ğŸ§ª E2E test snackager
      #   run: yarn test --ci --runInBand --testPathPattern=__integration-tests__

      - name: ğŸ— Setup Google Cloud SDK
        uses: ./.github/actions/setup-google-cloud
        with:
          project-id: exponentjs
          project-zone: us-central1-f
          project-cluster: exp-central
          service-key: ${{ secrets.GCLOUD_KEY }}

      - name: Build
        run: ENVIRONMENT=production skaffold build --filename snackager/skaffold.yaml --file-output snackager/build.json
        working-directory: ./

      - name: Notify build on Slack
        uses: 8398a7/action-slack@v3
        if: failure() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy != 'deploy'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_SNACK }}
        with:
          channel: '#snack'
          status: ${{ job.status }}
          author_name: Build Snackager for Production
          fields: message,commit,author,took

      - name: Add change cause
        run: kustomize edit add annotation kubernetes.io/change-cause:"Github Actions deploying $GITHUB_SHA at $(date)"
        working-directory: snackager/k8s/production

      - name: Deploy to production
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy == 'deploy'
        run: ENVIRONMENT=production skaffold deploy --filename snackager/skaffold.yaml --status-check true --build-artifacts snackager/build.json
        working-directory: ./

      - name: Configure kubectl for new cluster
        run: gcloud container clusters get-credentials --region us-central1 general-central

      - name: Deploy to production in new cluster
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy == 'deploy'
        run: ENVIRONMENT=production skaffold deploy --filename snackager/skaffold.yaml --status-check true --build-artifacts snackager/build.json
        working-directory: ./

      - name: Prune docker images
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy == 'deploy'
        run: ./bin/prune-gcr snackager
        working-directory: ./

      - name: Notify deploy on Slack
        uses: 8398a7/action-slack@v3
        if: always() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy == 'deploy'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_SNACK }}
        with:
          channel: '#snack'
          status: ${{ job.status }}
          author_name: Deploy Snackager to Production
          fields: message,commit,author,took
