name: SnackagerProduction

defaults:
  run:
    working-directory: snackager

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'type "deploy" to confirm deploy to production (main branch only)'
        required: false
  push:
    branches: [main]
    paths:
      - .github/workflows/snackager-production.yml
      - snackager/**
      - packages/snack-sdk/**
      - .eslint*
      - .prettier*
      - yarn.lock

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Decrypt secrets
        uses: sliteteam/github-action-git-crypt-unlock@a09ea5079c1b0e1887d4c8d7a4b20f00b5c2d06b
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          project_id: exponentjs
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true

      - name: Install Google Cloud components
        run: gcloud components install kubectl kustomize skaffold

      - name: Configure Google Cloud SDK
        run: |
          gcloud config set project exponentjs
          gcloud config set compute/zone us-central1-f
          gcloud config set container/cluster exp-central
          gcloud container clusters get-credentials exp-central
          gcloud auth configure-docker gcr.io

      - run: npm i -g npm@6.14.16
        working-directory: ../
      - run: yarn install --ignore-scripts --frozen-lockfile
      - run: yarn build
        working-directory: packages/snack-content
      - run: yarn build
        working-directory: packages/snack-sdk
      - run: yarn lint --max-warnings 0
      - run: yarn test --ci --testPathIgnorePatterns=__integration-tests__
      - run: yarn test --ci --runInBand --testPathPattern=__integration-tests__

      - name: Build
        run: ENVIRONMENT=production skaffold build --filename snackager/skaffold.yaml --file-output snackager/build.json
        working-directory: ./

      - name: Notify build on Slack
        uses: 8398a7/action-slack@v3
        if: failure() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy != 'deploy'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_SNACK }}
        with:
          channel: '#snack'
          status: ${{ job.status }}
          author_name: Build Snackager for Production
          fields: message,commit,author,took

      - name: Add change cause
        run: kustomize edit add annotation kubernetes.io/change-cause:"Github Actions deploying $GITHUB_SHA at $(date)"
        working-directory: snackager/k8s/production

      - name: Deploy to production
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy == 'deploy'
        run: ENVIRONMENT=production skaffold deploy --filename snackager/skaffold.yaml --status-check true --build-artifacts snackager/build.json
        working-directory: ./

      - name: Configure kubectl for new cluster
        run: gcloud container clusters get-credentials --region us-central general-central

      - name: Deploy to production in new cluster
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy == 'deploy'
        run: ENVIRONMENT=production skaffold deploy --filename snackager/skaffold.yaml --status-check true --build-artifacts snackager/build.json
        working-directory: ./

      - name: Prune docker images
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy == 'deploy'
        run: ./bin/prune-gcr snackager
        working-directory: ./

      - name: Notify deploy on Slack
        uses: 8398a7/action-slack@v3
        if: always() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.inputs.deploy == 'deploy'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_SNACK }}
        with:
          channel: '#snack'
          status: ${{ job.status }}
          author_name: Deploy Snackager to Production
          fields: message,commit,author,took
